version: "3.7"
services:
  zheng_tvm_local_dev:
    image: tzhenghao/tvm/local_dev
    build:
      context: .
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles: ["dev"]
