version: "3.7"
services:
  tvm_local_dev_cpu:
    image: my-tvm/local_dev/cpu
    build:
      context: .
    volumes:
      - .:/app
    profiles: ["dev"]
  tvm_local_dev_gpu:
    image: my-tvm/local_dev/gpu
    build:
      context: .
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles: ["dev"]
