[tool.black]
line-length=79
target-version = [
  "py37",
  "py38",
  "py39",
  "py310",
]
exclude = '''
/(
    \.eggs/
  | \.git/
  | \.tox/
  | \.venv/
  | _build/
  | build/
  | dist/
)
'''

[tool.isort]
profile = "black"
include_trailing_comma = true
line_length = 79
import_heading_stdlib = "Standard imports"
import_heading_thirdparty = "Third party imports"
import_heading_firstparty = "Lexer imports"
force_alphabetical_sort_within_sections = true
group_by_package = true